### ISSUE TITLE
Invalid MEX File Error

### ISSUE THREAD

**Issue by jdc5549** [mitre-rise/coupled-networks#3]
Getting an error when I try to follow the instructions to build the smart grid optimizer. The build completes successfully, but when it gets to the "Testing Solver" portion I get the following error:

`Invalid MEX-file '/home/workstation1/Documents/James_C/coupled-networks/src/mexosi_v03/mexosi.mexa64':
/home/workstation1/Documents/James_C/coupled-networks/src/mexosi_v03/Cbc-2.8.9/lib/libOsiCbc.so.3: undefined symbol:
_ZN8CbcModelC1ERK18OsiSolverInterface`

I'm using MATLAB R2015a on an Ubuntu 18.04.4 machine. Any guidance would be appreciated.

**Comment by phines** [comment]
It looks like this is an error with the Cbc build.  Have you tried to build Cbc separately to see if that works on your machine?

**Comment by jdc5549** [comment]
I tried building Cbc separately and then running the MATLAB script without building and I received the same error. Would you be able to let me know the Linux OS you tested on?

**Comment by veneman** [comment]
We last built it successfully on CentOS 7.

**Comment by veneman** [comment]
I just pushed some updates that hadn't made it to Github yet. They enable use with Python 3, networkx 2+ and MATLAB 2019a. There's also an update to the readme that could be useful: 

In order for the mex executable to find the shared library, it may be necessary to update an environment variable. ```export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${PROJECT_DIRECTORY}/src/mexosi_v03/Cbc-2.8.9/lib```. You can place this in your ```~/.bashrc``` or whatever equivalent, source it, and restart matlab so the new envirnoment variable is used.

**Comment by jdc5549** [comment]
I was able to get this to work by running in a CentOS 7 virtual machine, however the original error still occurs in Ubuntu 18.04. I've also replicated this error on a second machine with Ubuntu 18.04. This was using the recently pushed updates in MATLAB 2019a as well.
